### ISSUE TITLE
Having trouble pushing code to github in order to create my own Portfolio. Please help

### ISSUE THREAD

**Issue by aladin94** [cobidev/gatsby-simplefolio#1]
After making the necessary changes to the starter template, and trying to host it on either Github Pages or Netlify, I receive the same errors at the command line which prevent me from doing so:

"‼ Some of your tasks use `git add` command. Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index."

After continuing the process, I receive this error: "Running tasks for *.+(json|css|md) [failed]", which loops and never ends.

Has anyone else faced this problem? Are there files that I should omit or edit? PLEASE HELP me as I would love to use this portfolio template. Thanks in advance!

**Comment by cobidev** [comment]
Hello Aladin! Hope you're doing well.

Ok so seems to be an error with Git, am I right?

Did you remove the origin repository? And then did you link the project into your custom repository?

**Comment by cobidev** [comment]
@aladin94 I'm also planning to do a walkthrough video on how to set up Simplefolio with Gatsby. So you can follow up the process from start to finish. Hoping to get this uploaded at the end of the weekend.

Additional to that, can you send me a screenshot of the error you're getting?

**Comment by aladin94** [comment]
Hi Jacobo! 

Thank you for responding so soon, and for creating such a great template. 
Yes, I believe Git is the problem. I can run it perfectly on my local Host, but while trying to push it to my github pages repo, I receive those errors. I've attached a screenshot below:

![gitpic](https://user-images.githubusercontent.com/24710583/75510865-4aaf1a00-59ba-11ea-81cc-151417103a07.png)

Thank you.

**Comment by aladin94** [comment]
Also, after removing the "git add" comments from the package.json, I get rid of the first error. But still receive the "Failed" messages on Git


![gitadd](https://user-images.githubusercontent.com/24710583/75510924-7cc07c00-59ba-11ea-95c7-e44c4f81e471.png)

**Comment by cobidev** [comment]
Ok, just to clarify what lint-staged does 🙂

That script only runs when you "commit" a change, it'll trigger eslint to fix all the formatted code and the it'll add those changes using git add

**Comment by cobidev** [comment]
@aladin94 

Ok, just to clarify what lint-staged does 🙂

That script only runs when you "commit" a change, it'll trigger eslint to fix all the unformatted code and then it'll add those changes using git add. So I think you should leave it like that, just as when you cloned the project for the first time.

The other thing I'm seeing is that you don't have a .gitignore file, or am I wrong? Maybe when you try to push your changes, the lint-staged script is also grabbing all the files from node_modules/
so it never ends checking each file for lint validations.

The node_modules cannot be pushed when trying to deploy.

**Comment by cobidev** [comment]
Don't worry if you are still struggling. I'll record a video of me explaining how to setup and deploy the project properly on Netlify!

**Comment by aladin94** [comment]
Oh okay. I honestly didn't know what most of the files were for and tried to reduce the amount of files, since GitHub pages wouldn't let me push such a large file.

So I should not delete any files in order to avoid this mistake? 

Also, do you know if I would need an Index.html file in order for github.io to render it properly? Or should I just keep the code as it is and use Netlify? Sorry for so many questions, I'm new to web development. Thanks again

**Comment by cobidev** [comment]
@aladin94 

The thing is that Gatsby works different. If you want to host your website on Github Pages you need to install a package called `gh-pages` and then add their corresponding configuration (additional stuff I didn't want to add), I recommend to use Netlify because it simplifies the way of deploying Gatsby apps/websites. Because the only thing you need to do is to link your repo, and then specify the build command on Netlify and they will start the process of deploy.

In order to work properly, don't delete any files you see on the package.json. If you want to edit or modify some stuff, let me know, so I can help you with that :)

But as far I know, you only need to make a successfully deploy. And with Netlify you can do that!

Also, please check that the node_modules folder is ignored, do not need that on the repo. Only for local environment.

Hope it helps!

I left a related link about GitHub pages + Gatsby: https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/

If you feel comfortable with the setup, let me know!

**Comment by aladin94** [comment]
Okay, I managed to get it to work on Netlify. Thank you very much for your help!

**Comment by levi-source03** [comment]
What ended up being the solution to fix this issue and get it running on Netlify? Running into a similar issue and it's preventing me from making the commit that has my portfolio. :(
